=== adrianapapac/webb3/L1/resor.dtd
<!ELEMENT destination_object (destination+)>
    <!ELEMENT destination (name, cost, todo, food, link)>
    <!ATTLIST destination countries (thailand|bali|filippinerna) #REQUIRED>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT cost (#PCDATA)>
    <!ELEMENT todo (#PCDATA)>
    <!ELEMENT food (#PCDATA)>
    <!ELEMENT link (#PCDATA)>
    <!ATTLIST link url CDATA #REQUIRED>

=== adrianapapac/webb3/L1/bali.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE destination_object SYSTEM "resor.dtd"> 

<destination_object>

    <destination countries="bali">
        <name>Canggu</name>
        <cost>Average spend per day = 48$</cost>
        <todo>La brisa terrace, Batu bolong beach, Pura tanah lot temple</todo>
        <food>Nasi goreng</food>
        <link url="https://balibuddies.com/areas-of-bali/canggu/">Länk till reseguide</link>
    </destination>


    <destination countries="bali">
        <name>Uluwatu</name>
        <cost>Average spend per day = 51$</cost>
        <todo>Padang beach, Uluwatu temple, Karang cliff</todo>
        <food>Mie goreng</food>
        <link url="https://balibuddies.com/uluwatu-beach/">Länk till reseguide</link>
    </destination>

    <destination countries="bali">
        <name>Ubud</name>
        <cost>Average spend per day = 42$</cost>
        <todo>Monkey forest, rice tegallang, secret waterfall</todo>
        <food>Chicken satay</food>
        <link url="https://balibuddies.com/areas-of-bali/ubud/">Länk till reseguide</link>
    </destination>

</destination_object>

=== adrianapapac/webb3/L1/filippinerna.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE destination_object SYSTEM "resor.dtd">

<destination_object>

    <destination countries="filippinerna">
        <name>Manila</name>
        <cost>Average spend per day = 54$</cost>
        <todo>National museum, Straight up sky bar, Shangri-la plaza</todo>
        <food>Adobo chicken</food>
        <link url="https://philippines.travel/destinations/manila">Länk till reseguide</link>
    </destination>


    <destination countries="filippinerna">
        <name>Palawan</name>
        <cost>Average spend per day = 44$</cost>
        <todo>Snorkling, Island hoping, safari</todo>
        <food>Bulalo</food>
        <link url="https://www.theadventurousflashpacker.com/philippines-palawan-travel-overview/">Länk till reseguide</link>
    </destination>

    <destination countries="filippinerna">
        <name>boracay</name>
        <cost>Average spend per day = 46$</cost>
        <todo>white beach, zipline, helicopter tour</todo>
        <food>Chicken nasal</food>
        <link url="https://itsmorefuninthephilippines.co.uk/boracay/">Länk till reseguide</link>
    </destination>

</destination_object>

=== adrianapapac/webb3/L1/thailand.xml
<?xml version="1.0" encoding="UTF-8" standalone ="no"?> 
<!DOCTYPE destination_object SYSTEM "resor.dtd">
<destination_object>

    <destination countries="thailand">
        <name>Bangkok</name>
        <cost>Average spend per day = 43$</cost>
        <todo>Bangla road, Temple of the emerald buddha, Wat pho palace</todo>
        <food>Pad thai</food>
        <link url="https://www.willflyforfood.net/the-first-timers-travel-guide-to-bangkok/">Länk till reseguide</link>
    </destination>


    <destination countries="thailand">
        <name>Phuket</name>
        <cost>Average spend per day = 37$</cost>
        <todo>Big buddha Phuket, Snorkling, Zip line</todo>
        <food>Red curry</food>
        <link url="https://www.inthailand.travel/phuket/">Länk till reseguide</link>
    </destination>

    <destination countries="thailand">
        <name>Phi Phi Islands</name>
        <cost>Average spend per day = 41$</cost>
        <todo>Maya bay, Long beach, Loh lana Hiking</todo>
        <food>Massaman curry</food>
        <link url="https://theworldtravelguy.com/phi-phi-island-thailand/">Länk till reseguide</link>
    </destination>

</destination_object>
